Sprint 3
Nixyar/middle.messenger.praktikum.yandex pull request #18
Opened 2022-07-10 13:16 UTC by Nixyar

2022-07-14 06:13 UTC, agadoev requested changes
Привет
Спасибо за работу, я отметил те места, которые стоит поправить. Попробуй это пофиксить и двинемся дальше :)

2022-07-14 06:13 UTC, agadoev commented on package.json
> +    "serve": "parcel src/index.html --port=3000"
Стоит добавить скрипт для запуска eslint'a

2022-07-14 06:13 UTC, agadoev commented on src/pages/auth-page/auth-page.ts
> +      onSubmit: (evt: SubmitEvent) => {
этот функционал дублируется тут и в registration page. В дальнейшем он может потребоваться на других страницах. Его стоит вынести и в отдельную функцию и переиспользовать. Например, можешь вынести его на уровень сервисов

2022-07-14 06:13 UTC, agadoev commented on src/pages/auth-page/auth-page.ts
> +          http.post('/auth/signin', { data: values })
Наши UI компоненты не должны напрямую делать HTTP запросы. Обычно между слоем запросов и слоем UI есть слой контроллеров, но у тебя это слой я так понял называется сервисами. Почему бы и нет, суть не меняется. В общем лучше перенести все вызовы HTTP из UI компонентов в сервисы, потому что у них разная ответственность и при изменении логики мы не должны лезть в UI

2022-07-14 06:13 UTC, agadoev commented on src/services/HTTPTransport.service.ts
> +            if (method === 'GET') {
Почему бы не воспользоваться тут Methods.GET вместо строковой константы?

2022-07-14 06:13 UTC, agadoev commented on src/pages/settings-page/settings-page.ts
> +                        if (values.hasOwnProperty(key)) {
Тут можно убрать if (values.hasOwnProperty(key)), потому что мы итак пробегаемся по объекту values и этот if всегда будет возвращать true

2022-07-14 06:13 UTC, agadoev commented on src/pages/settings-page/settings-page.ts
> +                    const sendProfileInfo = {};
Почему бы не написать тип для sendProfileInfo? в таком случае не придется явно приводить этот объект к any

2022-07-14 09:44 UTC, Nixyar commented on package.json
> +    "serve": "parcel src/index.html --port=3000"
Скрипт добавил

2022-07-14 14:41 UTC, Nixyar commented
https://deploy-preview-20--jolly-souffle-0cce95.netlify.app/

2022-07-15 15:21 UTC, agadoev commented
Привет

Все исправлено, кроме замены строковой константы на Methods.GET. Это может показаться мелочью, но такие мелочи в будущем будут отвлекать тебя и твоих коллег. Нужно стараться придерживаться единого стиля в коде и если где-то используется объект Methods для определения типа запроса, то нужно использовать его везде. И еще неплохо было бы добавить запуск stylelint при npm run lint.
Все остальное - ок, работу принимаю, удачи в следующем спринте :)

2022-07-18 21:25 UTC, merged